const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Behaviors.Timer,
		C3.Behaviors.Pin,
		C3.Behaviors.Bullet,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Plugins.AJAX,
		C3.Plugins.TextBox,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Json,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.AJAX.Acts.SetHeader,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Cnds.OnAnyError,
		C3.Plugins.Json.Cnds.HasKey
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Physics: 0},
	{Timer: 0},
	{Peg: 0},
	{bgtest: 0},
	{Pin: 0},
	{shooter: 0},
	{Bullet: 0},
	{ball: 0},
	{wall: 0},
	{Sine: 0},
	{bucket: 0},
	{bucketHitbox: 0},
	{CoinFlip: 0},
	{bucketVictoryHitbox: 0},
	{bucketVictory: 0},
	{wallVictory: 0},
	{Fade: 0},
	{ballTrail: 0},
	{Bumper: 0},
	{demo4bg: 0},
	{Logo: 0},
	{Demo1: 0},
	{AJAX: 0},
	{AJAXTest: 0},
	{Demo2: 0},
	{Demo3: 0},
	{Login: 0},
	{BallCount: 0},
	{FreeBall: 0},
	{OrangePegsRemaining: 0},
	{ScoreText: 0},
	{TotalScoreText: 0},
	{TurnCountText: 0},
	{YouWin: 0},
	{ScoreCountUpwards: 0},
	{MultiplierText: 0},
	{UsernameInput: 0},
	{PasswordInput: 0},
	{Back: 0},
	{LoginStatus: 0},
	{Register: 0},
	{WallUI: 0},
	{scorebug: 0},
	{crystals: 0},
	{floorui: 0},
	{BallsLeft: 0},
	{fevermeter: 0},
	{FreeBallUI: 0},
	{bluepegs: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{JSON: 0},
	{GameReady: 0},
	{BallActive: 0},
	{NumberOfOrangePegsInLevel: 0},
	{OrangePegsLoadedInLevel: 0},
	{EvilPegSpawned: 0},
	{PurplePegSpawned: 0},
	{CoinFlipWin: 0},
	{TurnCount: 0},
	{ScoreTotal: 0},
	{ScoreMultiplier: 0},
	{ScoreVictoryScreenCounter: 0},
	{BluePegsDestroyedInOneTurn: 0},
	{OrangePegsDestroyedInOneTurn: 0},
	{EndOfTurn: 0},
	{Username: 0},
	{Password: 0},
	{JWT: 0}
];

self.InstanceType = {
	Peg: class extends self.ISpriteInstance {},
	bgtest: class extends self.ISpriteInstance {},
	shooter: class extends self.ISpriteInstance {},
	ball: class extends self.ISpriteInstance {},
	wall: class extends self.ISpriteInstance {},
	bucket: class extends self.ISpriteInstance {},
	bucketHitbox: class extends self.ISpriteInstance {},
	CoinFlip: class extends self.ISpriteInstance {},
	bucketVictoryHitbox: class extends self.ISpriteInstance {},
	bucketVictory: class extends self.ISpriteInstance {},
	wallVictory: class extends self.ISpriteInstance {},
	ballTrail: class extends self.ISpriteInstance {},
	Bumper: class extends self.ISpriteInstance {},
	demo4bg: class extends self.ISpriteInstance {},
	Logo: class extends self.ITextInstance {},
	Demo1: class extends self.ITextInstance {},
	AJAX: class extends self.IInstance {},
	AJAXTest: class extends self.ITextInstance {},
	Demo2: class extends self.ITextInstance {},
	Demo3: class extends self.ITextInstance {},
	Login: class extends self.ITextInstance {},
	BallCount: class extends self.ITextInstance {},
	FreeBall: class extends self.ITextInstance {},
	OrangePegsRemaining: class extends self.ITextInstance {},
	ScoreText: class extends self.ITextInstance {},
	TotalScoreText: class extends self.ITextInstance {},
	TurnCountText: class extends self.ITextInstance {},
	YouWin: class extends self.ITextInstance {},
	ScoreCountUpwards: class extends self.ITextInstance {},
	MultiplierText: class extends self.ITextInstance {},
	UsernameInput: class extends self.ITextInputInstance {},
	PasswordInput: class extends self.ITextInputInstance {},
	Back: class extends self.ITextInstance {},
	LoginStatus: class extends self.ITextInstance {},
	Register: class extends self.ITextInstance {},
	WallUI: class extends self.ISpriteInstance {},
	scorebug: class extends self.ISpriteInstance {},
	crystals: class extends self.ISpriteInstance {},
	floorui: class extends self.ISpriteInstance {},
	BallsLeft: class extends self.ISpriteInstance {},
	fevermeter: class extends self.ISpriteInstance {},
	FreeBallUI: class extends self.ISpriteInstance {},
	bluepegs: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {}
}