const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Behaviors.Timer,
		C3.Behaviors.Pin,
		C3.Behaviors.Bullet,
		C3.Behaviors.Sin,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Physics: 0},
	{PegCircle: 0},
	{Timer: 0},
	{PegBrick: 0},
	{PegCurve: 0},
	{bgtest: 0},
	{Pin: 0},
	{shooter: 0},
	{Bullet: 0},
	{ball: 0},
	{wall: 0},
	{Sine: 0},
	{bucket: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{BallCount: 0},
	{bucketHitbox: 0},
	{YouWin: 0},
	{FreeBall: 0},
	{OrangePegsRemaining: 0},
	{BallActive: 0},
	{NumberOfOrangePegsInLevel: 0},
	{OrangePegsPlacedInLevel: 0},
	{PegSpawnHandler: 0},
	{EvilPegSet: 0}
];

self.InstanceType = {
	PegCircle: class extends self.ISpriteInstance {},
	PegBrick: class extends self.ISpriteInstance {},
	PegCurve: class extends self.ISpriteInstance {},
	bgtest: class extends self.ISpriteInstance {},
	shooter: class extends self.ISpriteInstance {},
	ball: class extends self.ISpriteInstance {},
	wall: class extends self.ISpriteInstance {},
	bucket: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	BallCount: class extends self.ITextInstance {},
	bucketHitbox: class extends self.ISpriteInstance {},
	YouWin: class extends self.ITextInstance {},
	FreeBall: class extends self.ITextInstance {},
	OrangePegsRemaining: class extends self.ITextInstance {}
}